public class BDEResponseMapper {
    public String OrganizationID;
    public String Company;
    public String Itemcode;
    public String Description;
    public String Project;
    public String Warehouse;
    public String WarehouseDesc;
    public String WarehouseType;
    public String BusinessCode;
    public String BusinessName;
    public String InvUnit;
    public String OnHandStock = '0';
    public String FreeStock = '0';
    public String UnitBasicPrice = '0';
    public String TransactionAgingDays = '0';
    public String messageType;
    public String message;
    public String CommittedQty = '0'; //added by Pankaj & Shreela on 24-02-2022
    public BDEResponseMapper(){}
}